'use server';

/**
 * @fileOverview Summarizes recent alerts and provides potential actions for veterinarians and farmers.
 * It also sends a Telegram notification for critical alerts.
 *
 * - summarizeAlerts - A function that generates a summary of recent alerts and potential actions.
 * - SummarizeAlertsInput - The input type for the summarizeAlerts function.
 * - SummarizeAlertsOutput - The return type for the summarizeAlerts function.
 */

import {ai} from '@/ai/genkit';
import { sendTelegramNotification } from '@/services/telegram-service';
import {z} from 'genkit';

const SummarizeAlertsInputSchema = z.object({
  alerts: z
    .string()
    .describe("A list of recent alerts generated by the system, in JSON string format."),
});
export type SummarizeAlertsInput = z.infer<typeof SummarizeAlertsInputSchema>;

const SummarizeAlertsOutputSchema = z.object({
  summary: z.string().describe('A summary of the recent alerts.'),
  suggestedActions: z.string().describe('Suggested actions to take based on the alerts.'),
  notificationSent: z.boolean().describe('Whether a notification was sent.'),
});
export type SummarizeAlertsOutput = z.infer<typeof SummarizeAlertsOutputSchema>;

export async function summarizeAlerts(input: SummarizeAlertsInput): Promise<SummarizeAlertsOutput> {
  return summarizeAlertsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeAlertsPrompt',
  input: {schema: z.object({alerts: z.string()})},
  output: {schema: z.object({
    summary: z.string().describe('A summary of the recent alerts.'),
    suggestedActions: z.string().describe('Suggested actions to take based on the alerts.'),
  })},
  prompt: `You are an AI assistant helping veterinarians and farmers understand recent alerts from their farm monitoring system.

  Your task is to summarize the alerts and suggest potential actions to take.

  Recent Alerts (JSON format):
  {{{alerts}}}

  Summary:
  Suggested Actions:
  `,
});

const summarizeAlertsFlow = ai.defineFlow(
  {
    name: 'summarizeAlertsFlow',
    inputSchema: SummarizeAlertsInputSchema,
    outputSchema: SummarizeAlertsOutputSchema,
  },
  async input => {
    let notificationSent = false;
    // Check for critical alerts and send notification
    try {
      const alerts = JSON.parse(input.alerts);
      const criticalAlert = alerts.find((alert: any) => alert.severity === "Kritik");
      
      if (criticalAlert) {
        const message = `🚨 *KRİTİK UYARI* 🚨\n\n*Hayvan ID:* ${criticalAlert.animalId}\n*Mesaj:* ${criticalAlert.message}\n\nLütfen acilen kontrol ediniz!`;
        const result = await sendTelegramNotification(message);
        if (result.success) {
          notificationSent = true;
        }
      }
    } catch (e) {
      console.error("Failed to parse alerts or send notification:", e);
    }

    const {output} = await prompt({alerts: input.alerts});
    return {
        ...output!,
        notificationSent,
    };
  }
);
